name: Build plugin

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Disable copy to BD
      uses: jacobtomlinson/gha-find-replace@v3
      with:
        find: "copyToBD: true"
        replace: "copyToBD: false"
        regex: false
        include: ".zplrc.js"
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Build plugin
      run: npm run build BetterSBM
    - name: Archive plugin build
      uses: actions/upload-artifact@v3
      with:
        name: BetterSBM.plugin.js
        path: build/BetterSBM.plugin.js
        if-no-files-found: error
